"""
╔═══════════════════════════════════════════════════════════════════════════════╗
║                    GAME STATE ENGINE                                          ║
║                                                                               ║
║  Persistent game state management for vibe coding workflow.                   ║
║                                                                               ║
║  RESPONSIBILITIES:                                                            ║
║  1. Maintain persistent game state across requests                            ║
║  2. Track user edits and modifications                                        ║
║  3. Enable partial regeneration (only affected parts)                         ║
║  4. Provide state diff for incremental updates                                ║
║  5. Support undo/redo of changes                                              ║
║  6. Merge AI-generated content with user modifications                        ║
║                                                                               ║
║  VIBE CODING FLOW:                                                            ║
║  1. User: "Create a forest game with fairies"                                 ║
║     → Full generation → GameState created                                     ║
║                                                                               ║
║  2. User: "Add a campfire to scene 1"                                         ║
║     → Partial edit → Only scene 1 regenerated                                 ║
║     → GameState.apply_edit() → New state                                      ║
║                                                                               ║
║  3. User: "Make the fairy friendlier"                                         ║
║     → NPC edit only → Only NPC dialogue regenerated                           ║
║     → GameState.patch_npc() → Updated state                                   ║
╚═══════════════════════════════════════════════════════════════════════════════╝
"""

import logging
import json
import copy
import hashlib
from datetime import datetime
from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any, Tuple
from enum import Enum

from app.agents.prompt_interpreter import GameConcept
from app.agents.planner_agent import GamePlan


logger = logging.getLogger(__name__)


# ═══════════════════════════════════════════════════════════════════════════════
#  ENUMS & TYPES
# ═══════════════════════════════════════════════════════════════════════════════


class EditType(str, Enum):
    """Types of edits that can be applied."""

    # Scene-level
    ADD_SCENE = "add_scene"
    REMOVE_SCENE = "remove_scene"
    UPDATE_SCENE = "update_scene"
    REORDER_SCENES = "reorder_scenes"

    # Object-level
    ADD_OBJECT = "add_object"
    REMOVE_OBJECT = "remove_object"
    MOVE_OBJECT = "move_object"
    UPDATE_OBJECT = "update_object"

    # NPC-level
    ADD_NPC = "add_npc"
    REMOVE_NPC = "remove_npc"
    UPDATE_NPC = "update_npc"
    UPDATE_NPC_DIALOGUE = "update_npc_dialogue"

    # Challenge-level
    ADD_CHALLENGE = "add_challenge"
    REMOVE_CHALLENGE = "remove_challenge"
    UPDATE_CHALLENGE = "update_challenge"

    # Route-level
    ADD_ROUTE = "add_route"
    REMOVE_ROUTE = "remove_route"
    UPDATE_ROUTE = "update_route"

    # Global
    UPDATE_THEME = "update_theme"
    UPDATE_NARRATIVE = "update_narrative"
    UPDATE_GOAL = "update_goal"

    # Full regeneration
    REGENERATE_ALL = "regenerate_all"
    REGENERATE_SCENE = "regenerate_scene"
    REGENERATE_DIALOGUE = "regenerate_dialogue"


class StateStatus(str, Enum):
    """Status of the game state."""

    EMPTY = "empty"
    PLANNING = "planning"
    GENERATING = "generating"
    READY = "ready"
    EDITING = "editing"
    ERROR = "error"


# ═══════════════════════════════════════════════════════════════════════════════
#  EDIT RECORD
# ═══════════════════════════════════════════════════════════════════════════════


@dataclass
class EditRecord:
    """
    Record of a single edit applied to the game state.

    Used for undo/redo and tracking what changed.
    """

    edit_id: str
    edit_type: EditType
    timestamp: datetime

    # What was edited
    target_type: str  # "scene", "npc", "challenge", "object", "route", "global"
    target_id: Optional[str] = None  # ID of the target (e.g., scene_name, npc_id)

    # The edit details
    instruction: str = ""  # User's natural language instruction
    changes: Dict[str, Any] = field(default_factory=dict)  # Structured changes

    # Before/after for undo
    before_state: Optional[Dict[str, Any]] = None
    after_state: Optional[Dict[str, Any]] = None

    # Metadata
    ai_generated: bool = True  # Was this generated by AI or manual?
    confidence: float = 1.0

    def to_dict(self) -> Dict[str, Any]:
        return {
            "edit_id": self.edit_id,
            "edit_type": self.edit_type.value,
            "timestamp": self.timestamp.isoformat(),
            "target_type": self.target_type,
            "target_id": self.target_id,
            "instruction": self.instruction,
            "changes": self.changes,
            "ai_generated": self.ai_generated,
            "confidence": self.confidence,
        }


# ═══════════════════════════════════════════════════════════════════════════════
#  GAME STATE
# ═══════════════════════════════════════════════════════════════════════════════


@dataclass
class GameState:
    """
    Complete persistent state of a game being created/edited.

    This is the central data structure for vibe coding - it maintains
    the full game state and supports incremental modifications.
    """

    # Identity
    game_id: str
    version: int = 1
    created_at: datetime = field(default_factory=datetime.utcnow)
    updated_at: datetime = field(default_factory=datetime.utcnow)

    # Status
    status: StateStatus = StateStatus.EMPTY

    # Original input
    original_prompt: str = ""

    # Processed data (from pipeline)
    concept: Optional[GameConcept] = None
    plan: Optional[GamePlan] = None
    manifest: Optional[Dict[str, Any]] = None

    # Edit history
    edit_history: List[EditRecord] = field(default_factory=list)
    undo_stack: List[EditRecord] = field(default_factory=list)

    # User modifications (not yet applied)
    pending_edits: List[Dict[str, Any]] = field(default_factory=list)

    # Cached data for fast access
    _scene_index: Dict[str, int] = field(default_factory=dict)
    _npc_index: Dict[str, str] = field(default_factory=dict)  # npc_id → scene_name
    _challenge_index: Dict[str, str] = field(default_factory=dict)

    # Dirty tracking (what needs regeneration)
    dirty_scenes: set = field(default_factory=set)
    dirty_npcs: set = field(default_factory=set)
    dirty_challenges: set = field(default_factory=set)
    dirty_routes: bool = False

    # Generation settings
    seed: Optional[int] = None
    platform_id: Optional[str] = None

    def __post_init__(self):
        """Build indexes after initialization."""
        self._rebuild_indexes()

    # ═══════════════════════════════════════════════════════════════════════
    #  INDEX MANAGEMENT
    # ═══════════════════════════════════════════════════════════════════════

    def _rebuild_indexes(self):
        """Rebuild all indexes from current manifest."""
        self._scene_index = {}
        self._npc_index = {}
        self._challenge_index = {}

        if not self.manifest:
            return

        # Index scenes - store multiple keys for flexible lookup
        for i, scene in enumerate(self.manifest.get("scenes", [])):
            scene_name = scene.get("scene_name", f"Scene {i + 1}")

            # Store primary name
            self._scene_index[scene_name] = i

            # Also store alternative formats for flexible lookup
            self._scene_index[f"scene_{i}"] = i
            self._scene_index[f"Scene {i + 1}"] = i
            self._scene_index[str(i)] = i
            self._scene_index[str(i + 1)] = i  # 1-indexed

            # Index NPCs in this scene
            for npc in scene.get("npcs", []):
                if isinstance(npc, str):
                    # NPC is a string ID
                    self._npc_index[npc] = scene_name
                elif isinstance(npc, dict):
                    npc_id = npc.get("npc_id") or npc.get("id")
                    if npc_id:
                        self._npc_index[npc_id] = scene_name

            # Index challenges in this scene
            for challenge in scene.get("challenges", []):
                if isinstance(challenge, str):
                    # Challenge is a string ID
                    self._challenge_index[challenge] = scene_name
                elif isinstance(challenge, dict):
                    ch_id = challenge.get("challenge_id") or challenge.get("id")
                    if ch_id:
                        self._challenge_index[ch_id] = scene_name

    def _normalize_scene_name(self, scene_ref: str) -> Optional[str]:
        """Normalize a scene reference to match index keys."""
        if not scene_ref:
            return None

        # Direct match
        if scene_ref in self._scene_index:
            return scene_ref

        # Try lowercase
        lower_ref = scene_ref.lower()
        for key in self._scene_index:
            if key.lower() == lower_ref:
                return key

        # Try extracting number from "Scene 1", "scene_0", etc.
        import re

        num_match = re.search(r"(\d+)", scene_ref)
        if num_match:
            num = int(num_match.group(1))
            # Try both 0-indexed and 1-indexed
            if f"scene_{num}" in self._scene_index:
                return f"scene_{num}"
            if f"Scene {num}" in self._scene_index:
                return f"Scene {num}"
            if f"scene_{num - 1}" in self._scene_index:
                return f"scene_{num - 1}"
            if f"Scene {num + 1}" in self._scene_index:
                return f"Scene {num + 1}"

        return None

    # ═══════════════════════════════════════════════════════════════════════
    #  STATE QUERIES
    # ═══════════════════════════════════════════════════════════════════════

    def get_scene(self, scene_name: str) -> Optional[Dict[str, Any]]:
        """Get a scene by name (flexible matching)."""
        if not self.manifest:
            return None

        # Try direct lookup first
        if scene_name in self._scene_index:
            idx = self._scene_index[scene_name]
            return self.manifest["scenes"][idx]

        # Try normalized lookup
        normalized = self._normalize_scene_name(scene_name)
        if normalized and normalized in self._scene_index:
            idx = self._scene_index[normalized]
            return self.manifest["scenes"][idx]

        return None

    def get_scene_by_index(self, index: int) -> Optional[Dict[str, Any]]:
        """Get a scene by index."""
        if not self.manifest:
            return None
        scenes = self.manifest.get("scenes", [])
        if 0 <= index < len(scenes):
            return scenes[index]
        return None

    def get_npc(self, npc_id: str) -> Optional[Tuple[Dict[str, Any], str]]:
        """Get an NPC by ID. Returns (npc, scene_name) or None."""
        if npc_id not in self._npc_index:
            return None

        scene_name = self._npc_index[npc_id]
        scene = self.get_scene(scene_name)
        if not scene:
            return None

        for npc in scene.get("npcs", []):
            if npc.get("npc_id") == npc_id or npc.get("id") == npc_id:
                return npc, scene_name

        return None

    def get_challenge(self, challenge_id: str) -> Optional[Tuple[Dict[str, Any], str]]:
        """Get a challenge by ID. Returns (challenge, scene_name) or None."""
        if challenge_id not in self._challenge_index:
            return None

        scene_name = self._challenge_index[challenge_id]
        scene = self.get_scene(scene_name)
        if not scene:
            return None

        for ch in scene.get("challenges", []):
            if ch.get("challenge_id") == challenge_id or ch.get("id") == challenge_id:
                return ch, scene_name

        return None

    def get_all_scenes(self) -> List[Dict[str, Any]]:
        """Get all scenes."""
        if not self.manifest:
            return []
        return self.manifest.get("scenes", [])

    def get_all_npcs(self) -> List[Tuple[Dict[str, Any], str]]:
        """Get all NPCs with their scene names."""
        result = []
        for scene in self.get_all_scenes():
            scene_name = scene.get("scene_name", "")
            for npc in scene.get("npcs", []):
                result.append((npc, scene_name))
        return result

    # ═══════════════════════════════════════════════════════════════════════
    #  STATE MODIFICATIONS
    # ═══════════════════════════════════════════════════════════════════════

    def apply_edit(self, edit: EditRecord) -> bool:
        """
        Apply an edit to the state.

        Returns True if successful.
        """
        try:
            # Store before state for undo
            edit.before_state = self._snapshot_target(edit.target_type, edit.target_id)

            # Apply based on edit type
            success = self._apply_edit_internal(edit)

            if success:
                # Store after state
                edit.after_state = self._snapshot_target(
                    edit.target_type, edit.target_id
                )

                # Add to history
                self.edit_history.append(edit)

                # Clear undo stack (new edit invalidates redo)
                self.undo_stack = []

                # Update metadata
                self.version += 1
                self.updated_at = datetime.utcnow()

                # Rebuild indexes
                self._rebuild_indexes()

            return success

        except Exception as e:
            logger.error(f"Failed to apply edit: {e}")
            return False

    def _apply_edit_internal(self, edit: EditRecord) -> bool:
        """Internal edit application logic."""

        if edit.edit_type == EditType.ADD_SCENE:
            return self._add_scene(edit.changes)

        elif edit.edit_type == EditType.REMOVE_SCENE:
            return self._remove_scene(edit.target_id)

        elif edit.edit_type == EditType.UPDATE_SCENE:
            return self._update_scene(edit.target_id, edit.changes)

        elif edit.edit_type == EditType.ADD_OBJECT:
            return self._add_object(edit.target_id, edit.changes)

        elif edit.edit_type == EditType.REMOVE_OBJECT:
            return self._remove_object(edit.target_id, edit.changes.get("object_id"))

        elif edit.edit_type == EditType.ADD_NPC:
            return self._add_npc(edit.target_id, edit.changes)

        elif edit.edit_type == EditType.REMOVE_NPC:
            return self._remove_npc(edit.changes.get("npc_id"))

        elif edit.edit_type == EditType.UPDATE_NPC:
            return self._update_npc(edit.target_id, edit.changes)

        elif edit.edit_type == EditType.ADD_CHALLENGE:
            return self._add_challenge(edit.target_id, edit.changes)

        elif edit.edit_type == EditType.REMOVE_CHALLENGE:
            return self._remove_challenge(edit.changes.get("challenge_id"))

        elif edit.edit_type == EditType.UPDATE_CHALLENGE:
            return self._update_challenge(edit.target_id, edit.changes)

        elif edit.edit_type == EditType.ADD_ROUTE:
            return self._add_route(edit.changes)

        elif edit.edit_type == EditType.REMOVE_ROUTE:
            return self._remove_route(
                edit.changes.get("from_scene"),
                edit.changes.get("to_scene"),
            )

        else:
            logger.warning(f"Unhandled edit type: {edit.edit_type}")
            return False

    def _snapshot_target(
        self, target_type: str, target_id: Optional[str]
    ) -> Optional[Dict]:
        """Take a snapshot of the edit target for undo."""
        if target_type == "scene" and target_id:
            scene = self.get_scene(target_id)
            return copy.deepcopy(scene) if scene else None
        elif target_type == "npc" and target_id:
            result = self.get_npc(target_id)
            return copy.deepcopy(result[0]) if result else None
        elif target_type == "challenge" and target_id:
            result = self.get_challenge(target_id)
            return copy.deepcopy(result[0]) if result else None
        elif target_type == "route":
            # Snapshot full routes list (routes are cross-scene)
            if self.manifest:
                return copy.deepcopy(self.manifest.get("routes", []))
            return None
        elif target_type == "object" and target_id:
            # Find object in any scene
            if self.manifest:
                for scene in self.manifest.get("scenes", []):
                    for obj in scene.get("actors", []) + scene.get("objects", []):
                        if isinstance(obj, dict):
                            oid = obj.get("object_id", obj.get("id", ""))
                            if oid == target_id:
                                return copy.deepcopy(obj)
            return None
        return None

    # ═══════════════════════════════════════════════════════════════════════
    #  SCENE OPERATIONS
    # ═══════════════════════════════════════════════════════════════════════

    def _add_scene(self, scene_data: Dict[str, Any]) -> bool:
        """Add a new scene."""
        if not self.manifest:
            self.manifest = {"scenes": [], "routes": [], "npcs": {}}

        scenes = self.manifest.setdefault("scenes", [])
        scene_data["scene_index"] = len(scenes)
        scenes.append(scene_data)

        self.dirty_scenes.add(scene_data.get("scene_name", f"scene_{len(scenes)}"))
        return True

    def _remove_scene(self, scene_name: str) -> bool:
        """Remove a scene by name."""
        if scene_name not in self._scene_index:
            return False

        idx = self._scene_index[scene_name]
        self.manifest["scenes"].pop(idx)

        # Update indexes of remaining scenes
        for i, scene in enumerate(self.manifest["scenes"]):
            scene["scene_index"] = i

        self.dirty_routes = True
        return True

    def _update_scene(self, scene_name: str, changes: Dict[str, Any]) -> bool:
        """Update a scene's properties."""
        scene = self.get_scene(scene_name)
        if not scene:
            return False

        for key, value in changes.items():
            scene[key] = value

        self.dirty_scenes.add(scene_name)
        return True

    # ═══════════════════════════════════════════════════════════════════════
    #  OBJECT OPERATIONS
    # ═══════════════════════════════════════════════════════════════════════

    def _add_object(self, scene_name: str, obj_data: Dict[str, Any]) -> bool:
        """Add an object to a scene."""
        # If no scene_name provided, try to use first scene
        if not scene_name:
            if self.manifest and self.manifest.get("scenes"):
                first_scene = self.manifest["scenes"][0]
                scene_name = first_scene.get("scene_name", "Scene 1")
                logger.info(
                    f"No scene specified, defaulting to first scene: {scene_name}"
                )
            else:
                logger.error(
                    "Cannot add object: no scene_name provided and no scenes exist"
                )
                return False

        scene = self.get_scene(scene_name)
        if not scene:
            logger.error(
                f"Cannot add object: scene '{scene_name}' not found. Available scenes: {list(self._scene_index.keys())[:10]}"
            )
            return False

        # Add to 'objects' list (used by manifest)
        objects = scene.setdefault("objects", [])

        # Create object entry with proper structure
        import uuid as _uuid

        obj_entry = {
            "object_id": obj_data.get("object_id") or f"obj_{str(_uuid.uuid4())[:8]}",
            "asset_name": obj_data.get("asset_name", "campfire"),
            "x": obj_data.get("x", 8),
            "y": obj_data.get("y", 8),
            "z_index": obj_data.get("z_index", 50),
            "type": obj_data.get("type", "interactive"),
            "walkable": obj_data.get("walkable", False),
            "interactable": obj_data.get("interactable", True),
        }

        # Merge any additional properties
        for key, value in obj_data.items():
            if key not in obj_entry:
                obj_entry[key] = value

        objects.append(obj_entry)

        # Also add to 'actors' if present (some manifests use this)
        if "actors" in scene:
            scene["actors"].append(obj_entry)

        logger.info(
            f"Added object '{obj_entry['asset_name']}' to scene '{scene_name}' at ({obj_entry['x']}, {obj_entry['y']})"
        )
        self.dirty_scenes.add(scene_name)
        return True

    def _remove_object(self, scene_name: str, object_id: str) -> bool:
        """Remove an object from a scene."""
        scene = self.get_scene(scene_name)
        if not scene:
            return False

        actors = scene.get("actors", [])
        scene["actors"] = [
            a
            for a in actors
            if a.get("id") != object_id and a.get("actor_id") != object_id
        ]

        self.dirty_scenes.add(scene_name)
        return True

    # ═══════════════════════════════════════════════════════════════════════
    #  NPC OPERATIONS
    # ═══════════════════════════════════════════════════════════════════════

    def _add_npc(self, scene_name: str, npc_data: Dict[str, Any]) -> bool:
        """Add an NPC to a scene."""
        scene = self.get_scene(scene_name)
        if not scene:
            return False

        npcs = scene.setdefault("npcs", [])
        npcs.append(npc_data)

        npc_id = npc_data.get("npc_id") or npc_data.get("id")
        if npc_id:
            self.dirty_npcs.add(npc_id)

        return True

    def _remove_npc(self, npc_id: str) -> bool:
        """Remove an NPC by ID."""
        result = self.get_npc(npc_id)
        if not result:
            return False

        npc, scene_name = result
        scene = self.get_scene(scene_name)
        if not scene:
            return False

        scene["npcs"] = [
            n
            for n in scene.get("npcs", [])
            if n.get("npc_id") != npc_id and n.get("id") != npc_id
        ]

        return True

    def _update_npc(self, npc_id: str, changes: Dict[str, Any]) -> bool:
        """Update an NPC's properties."""
        result = self.get_npc(npc_id)
        if not result:
            return False

        npc, scene_name = result
        for key, value in changes.items():
            npc[key] = value

        self.dirty_npcs.add(npc_id)
        return True

    # ═══════════════════════════════════════════════════════════════════════
    #  CHALLENGE OPERATIONS
    # ═══════════════════════════════════════════════════════════════════════

    def _add_challenge(self, scene_name: str, challenge_data: Dict[str, Any]) -> bool:
        """Add a challenge to a scene."""
        scene = self.get_scene(scene_name)
        if not scene:
            return False

        challenges = scene.setdefault("challenges", [])
        challenges.append(challenge_data)

        ch_id = challenge_data.get("challenge_id") or challenge_data.get("id")
        if ch_id:
            self.dirty_challenges.add(ch_id)

        return True

    def _remove_challenge(self, challenge_id: str) -> bool:
        """Remove a challenge by ID."""
        result = self.get_challenge(challenge_id)
        if not result:
            return False

        challenge, scene_name = result
        scene = self.get_scene(scene_name)
        if not scene:
            return False

        scene["challenges"] = [
            c
            for c in scene.get("challenges", [])
            if c.get("challenge_id") != challenge_id and c.get("id") != challenge_id
        ]

        return True

    def _update_challenge(self, challenge_id: str, changes: Dict[str, Any]) -> bool:
        """Update a challenge's properties."""
        result = self.get_challenge(challenge_id)
        if not result:
            return False

        challenge, scene_name = result
        for key, value in changes.items():
            challenge[key] = value

        self.dirty_challenges.add(challenge_id)
        return True

    # ═══════════════════════════════════════════════════════════════════════
    #  ROUTE OPERATIONS
    # ═══════════════════════════════════════════════════════════════════════

    def _add_route(self, route_data: Dict[str, Any]) -> bool:
        """Add a route between scenes."""
        if not self.manifest:
            return False

        routes = self.manifest.setdefault("routes", [])
        routes.append(route_data)

        self.dirty_routes = True
        return True

    def _remove_route(self, from_scene: str, to_scene: str) -> bool:
        """Remove a route between scenes."""
        if not self.manifest:
            return False

        routes = self.manifest.get("routes", [])
        self.manifest["routes"] = [
            r
            for r in routes
            if not (r.get("from_scene") == from_scene and r.get("to_scene") == to_scene)
        ]

        self.dirty_routes = True
        return True

    # ═══════════════════════════════════════════════════════════════════════
    #  UNDO/REDO
    # ═══════════════════════════════════════════════════════════════════════

    def undo(self) -> bool:
        """Undo the last edit.

        Handles two snapshot formats:
        - Full manifest (from edit pipeline): before_state has 'scenes' key
        - Partial target (from legacy editor): before_state is a single object
        """
        if not self.edit_history:
            return False

        edit = self.edit_history.pop()

        # Restore before state
        if edit.before_state is not None:
            if self._is_full_manifest(edit.before_state):
                # Full manifest restore (from edit pipeline)
                self.manifest = copy.deepcopy(edit.before_state)
            else:
                # Partial target restore (from legacy editor)
                self._restore_state(edit.target_type, edit.target_id, edit.before_state)

        # Push to undo stack
        self.undo_stack.append(edit)

        self.version += 1
        self.updated_at = datetime.utcnow()
        self._rebuild_indexes()

        return True

    def redo(self) -> bool:
        """Redo the last undone edit."""
        if not self.undo_stack:
            return False

        edit = self.undo_stack.pop()

        # Restore after state
        if edit.after_state is not None:
            if self._is_full_manifest(edit.after_state):
                # Full manifest restore (from edit pipeline)
                self.manifest = copy.deepcopy(edit.after_state)
            else:
                # Partial target restore (from legacy editor)
                self._restore_state(edit.target_type, edit.target_id, edit.after_state)

        # Push back to history
        self.edit_history.append(edit)

        self.version += 1
        self.updated_at = datetime.utcnow()
        self._rebuild_indexes()

        return True

    @staticmethod
    def _is_full_manifest(state: Dict) -> bool:
        """Check if state is a full manifest (has scenes) or a partial target."""
        return isinstance(state, dict) and "scenes" in state

    def _restore_state(self, target_type: str, target_id: str, state: Dict):
        """Restore a target to a previous state."""
        if not self.manifest:
            return

        if target_type == "scene":
            idx = self._scene_index.get(target_id)
            if idx is not None:
                self.manifest["scenes"][idx] = state

        elif target_type == "npc" and target_id:
            # Find NPC's scene and restore
            for scene in self.manifest.get("scenes", []):
                npcs = scene.get("npcs", [])
                for i, npc in enumerate(npcs):
                    if isinstance(npc, dict):
                        npc_id = npc.get("npc_id", npc.get("id", ""))
                        if npc_id == target_id:
                            npcs[i] = state
                            return

        elif target_type == "challenge" and target_id:
            # Find challenge's scene and restore
            for scene in self.manifest.get("scenes", []):
                challenges = scene.get("challenges", [])
                for i, ch in enumerate(challenges):
                    if isinstance(ch, dict):
                        ch_id = ch.get("challenge_id", ch.get("id", ""))
                        if ch_id == target_id:
                            challenges[i] = state
                            return

        elif target_type == "route":
            # Restore full routes list
            if isinstance(state, list):
                self.manifest["routes"] = state

        elif target_type == "object" and target_id:
            # Find object's scene and restore
            for scene in self.manifest.get("scenes", []):
                for key in ("actors", "objects"):
                    items = scene.get(key, [])
                    for i, obj in enumerate(items):
                        if isinstance(obj, dict):
                            obj_id = obj.get("object_id", obj.get("id", ""))
                            if obj_id == target_id:
                                items[i] = state
                                return

    # ═══════════════════════════════════════════════════════════════════════
    #  DIRTY TRACKING
    # ═══════════════════════════════════════════════════════════════════════

    def get_dirty_items(self) -> Dict[str, Any]:
        """Get all items that need regeneration."""
        return {
            "scenes": list(self.dirty_scenes),
            "npcs": list(self.dirty_npcs),
            "challenges": list(self.dirty_challenges),
            "routes": self.dirty_routes,
        }

    def clear_dirty(self):
        """Clear all dirty flags."""
        self.dirty_scenes = set()
        self.dirty_npcs = set()
        self.dirty_challenges = set()
        self.dirty_routes = False

    def has_dirty_items(self) -> bool:
        """Check if there are any items needing regeneration."""
        return bool(
            self.dirty_scenes
            or self.dirty_npcs
            or self.dirty_challenges
            or self.dirty_routes
        )

    # ═══════════════════════════════════════════════════════════════════════
    #  SERIALIZATION
    # ═══════════════════════════════════════════════════════════════════════

    def to_dict(self) -> Dict[str, Any]:
        """Serialize state to dictionary."""
        return {
            "game_id": self.game_id,
            "version": self.version,
            "created_at": self.created_at.isoformat(),
            "updated_at": self.updated_at.isoformat(),
            "status": self.status.value,
            "original_prompt": self.original_prompt,
            "concept": self.concept.to_dict() if self.concept else None,
            "plan": self.plan.to_dict() if self.plan else None,
            "manifest": self.manifest,
            "edit_history": [e.to_dict() for e in self.edit_history],
            "seed": self.seed,
            "platform_id": self.platform_id,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "GameState":
        """Deserialize state from dictionary."""
        state = cls(
            game_id=data["game_id"],
            version=data.get("version", 1),
            status=StateStatus(data.get("status", "empty")),
            original_prompt=data.get("original_prompt", ""),
            manifest=data.get("manifest"),
            seed=data.get("seed"),
            platform_id=data.get("platform_id"),
        )

        if data.get("created_at"):
            state.created_at = datetime.fromisoformat(data["created_at"])
        if data.get("updated_at"):
            state.updated_at = datetime.fromisoformat(data["updated_at"])

        state._rebuild_indexes()
        return state

    def get_hash(self) -> str:
        """Get a hash of the current state for change detection."""
        content = json.dumps(self.manifest or {}, sort_keys=True)
        return hashlib.sha256(content.encode()).hexdigest()[:16]


# ═══════════════════════════════════════════════════════════════════════════════
#  STATE MANAGER (In-Memory Cache)
# ═══════════════════════════════════════════════════════════════════════════════


class GameStateManager:
    """
    Manages game states across sessions.

    Provides in-memory caching with optional persistence.
    """

    def __init__(self):
        self._states: Dict[str, GameState] = {}
        self._logger = logging.getLogger("game_state_manager")

    def get(self, game_id: str) -> Optional[GameState]:
        """Get a game state by ID."""
        return self._states.get(game_id)

    def create(
        self,
        game_id: str,
        prompt: str = "",
        platform_id: Optional[str] = None,
        seed: Optional[int] = None,
    ) -> GameState:
        """Create a new game state."""
        state = GameState(
            game_id=game_id,
            original_prompt=prompt,
            platform_id=platform_id,
            seed=seed,
        )
        self._states[game_id] = state
        self._logger.info(f"Created new GameState: {game_id}")
        return state

    def get_or_create(
        self,
        game_id: str,
        prompt: str = "",
        platform_id: Optional[str] = None,
        seed: Optional[int] = None,
    ) -> GameState:
        """Get existing state or create new one."""
        existing = self.get(game_id)
        if existing:
            return existing
        return self.create(game_id, prompt, platform_id, seed)

    def save(self, state: GameState):
        """Save state to cache."""
        self._states[state.game_id] = state

    def delete(self, game_id: str) -> bool:
        """Delete a game state."""
        if game_id in self._states:
            del self._states[game_id]
            self._logger.info(f"Deleted GameState: {game_id}")
            return True
        return False

    def list_all(self) -> List[GameState]:
        """List all game states."""
        return list(self._states.values())

    def list_ids(self) -> List[str]:
        """List all game IDs."""
        return list(self._states.keys())

    def create_from_manifest(
        self,
        manifest: Dict[str, Any],
        game_id: Optional[str] = None,
    ) -> GameState:
        """
        Create a GameState from an existing manifest.

        Useful for loading a previously generated game for editing.
        """
        import uuid as _uuid

        # Extract game_id from manifest if not provided
        if not game_id:
            game_id = manifest.get("game", {}).get("id", str(_uuid.uuid4()))

        # Check if already exists
        existing = self.get(game_id)
        if existing:
            # Update manifest
            existing.manifest = manifest
            existing.status = StateStatus.READY
            existing._rebuild_indexes()
            return existing

        # Create new state from manifest
        state = GameState(
            game_id=game_id,
            status=StateStatus.READY,
            manifest=manifest,
            original_prompt=manifest.get("config", {}).get("goal_description", ""),
            seed=manifest.get("config", {}).get("seed"),
            platform_id=manifest.get("config", {}).get("platform_id"),
        )

        self._states[game_id] = state
        self._logger.info(f"Created GameState from manifest: {game_id}")

        return state

    def clear(self):
        """Clear all states."""
        self._states = {}


# Global instance
_state_manager: Optional[GameStateManager] = None


def get_state_manager() -> GameStateManager:
    """Get the global state manager instance."""
    global _state_manager
    if _state_manager is None:
        _state_manager = GameStateManager()
    return _state_manager
