"""
Core modules for game generation.
"""

from app.core.mechanics import (
    Mechanic,
    MechanicPack,
    MechanicCategory,
    ALL_MECHANICS,
    BASE_MECHANICS,
    MECHANICS_BY_PACK,
    get_mechanic,
    get_mechanics_by_pack,
    get_mechanics_by_affordance,
    get_mechanics_by_capability,
)

from app.core.challenge_templates import (
    ChallengeTemplate,
    FilledChallenge,
    Difficulty,
    Constraint,
    CHALLENGE_TEMPLATES,
    PARAMETER_CONSTRAINTS,
    get_template,
    get_all_templates,
    validate_filled_challenge,
    calculate_rewards,
    create_filled_challenge,
)

from app.core.npc_templates import (
    NPCTemplate,
    FilledNPC,
    NPCRole,
    NPCBehavior,
    NPC_TEMPLATES,
    get_npc_template,
    validate_filled_npc,
    get_placement_position,
)

from app.core.zone_system import (
    Zone,
    SemanticZone,
    ZoneType,
    SemanticPosition,
    OccupancyGrid,
    TileOccupancy,
    semantic_to_coordinates,
    convert_semantic_zone,
    convert_all_semantic_zones,
    bfs_reachable,
    validate_zone_reachability,
    calculate_z_index,
)

from app.core.mechanic_compatibility import (
    CompatibilityType,
    ProgressionOrder,
    CompatibilityRule,
    CategoryCompatibility,
    MechanicProgression,
    CompatibilityResult,
    CATEGORY_COMPATIBILITY,
    MECHANIC_COMPATIBILITY,
    MECHANIC_PROGRESSION,
    SCENE_MECHANIC_LIMITS,
    GAME_MECHANIC_LIMITS,
    SCENE_SAME_MECHANIC_LIMIT,
    SCENE_MECHANIC_EXCEPTIONS,
    check_scene_compatibility,
    check_progression_compatibility,
    check_game_loop_compatibility,
    suggest_compatible_mechanics,
    get_required_tutorials,
    get_mechanic_complexity,
    sort_by_progression,
    check_repetition_limits,
    check_scene_repetition,
    check_consecutive_repetition,
    validate_no_repetition,
    suggest_alternative_mechanics,
)

from app.core.difficulty_curve import (
    CurveType,
    AudienceType,
    DifficultyRange,
    DifficultyCurve,
    AUDIENCE_PRESETS,
    create_difficulty_curve,
    generate_linear_curve,
    generate_gentle_curve,
    generate_steep_curve,
    generate_wave_curve,
    generate_plateau_curve,
    validate_game_difficulty,
    suggest_mechanic_complexity_order,
    get_recommended_mechanics_for_scene,
)

from app.core.layout_patterns import (
    LayoutType,
    ZonePlacement,
    LayoutZone,
    Corridor,
    LayoutPattern,
    AppliedZone,
    AppliedCorridor,
    AppliedLayout,
    LAYOUT_PATTERNS,
    get_layout_pattern,
    get_patterns_for_scene_type as get_layout_patterns_for_scene,
    suggest_pattern as suggest_layout_pattern,
    apply_layout_pattern,
)

from app.core.npc_behaviors import (
    BehaviorState,
    TriggerType,
    StateTransition,
    BehaviorDefinition,
    BEHAVIORS,
    get_behavior,
    get_all_behaviors,
    get_behavior_for_role,
    create_patrol_path,
    get_next_waypoint,
    advance_patrol,
)

from app.core.tutorial_generator import (
    TutorialType,
    TutorialDialogue,
    TutorialChallenge,
    TutorialDefinition,
    TUTORIALS,
    get_tutorial,
    get_all_tutorials,
    needs_tutorial,
    generate_tutorial_scene,
    get_tutorial_hints,
    get_simplified_params,
)

from app.core.gameplay_loop_planner import (
    GoalType,
    GameplayStep,
    GameplayLoop,
    PlannedLoop,
    GamePlan,
    GAMEPLAY_LOOPS,
    get_loop,
    get_all_loops,
    get_loops_by_goal,
    get_loops_by_tag,
    suggest_loop,
    plan_loop,
    plan_from_goal,
    expand_goal_to_mechanics,
    plan_game,
    get_narrative_context,
    get_required_npc_roles,
    validate_loop_against_scene,
)

from app.core.scene_populator import (
    CellType,
    PlacedObject,
    OccupancyGrid,
    ClusterRule,
    LandmarkTemplate,
    PopulatorConfig,
    PopulatedScene,
    ScenePopulator,
    DEFAULT_CLUSTER_RULES,
    LANDMARKS,
    ZONE_LANDMARKS,
    ZONE_DECORATIONS,
    ZONE_DECORATION_WEIGHTS,
    poisson_disc_sampling,
    find_path_bfs,
    find_path_astar,
    reserve_corridor,
    reserve_corridor_natural,
    cluster_objects,
    distribute_decorations,
    terrain_noise,
    place_landmark,
    get_landmarks_for_zone,
    get_decorations_for_zone,
    populate_scene,
    get_scene_manifest,
)

__all__ = [
    # Mechanics
    "Mechanic",
    "MechanicPack",
    "MechanicCategory",
    "ALL_MECHANICS",
    "BASE_MECHANICS",
    "MECHANICS_BY_PACK",
    "get_mechanic",
    "get_mechanics_by_pack",
    "get_mechanics_by_affordance",
    "get_mechanics_by_capability",
    # Challenge Templates
    "ChallengeTemplate",
    "FilledChallenge",
    "Difficulty",
    "Constraint",
    "CHALLENGE_TEMPLATES",
    "PARAMETER_CONSTRAINTS",
    "get_template",
    "get_all_templates",
    "validate_filled_challenge",
    "calculate_rewards",
    "create_filled_challenge",
    # NPC Templates
    "NPCTemplate",
    "FilledNPC",
    "NPCRole",
    "NPCBehavior",
    "NPC_TEMPLATES",
    "get_npc_template",
    "validate_filled_npc",
    "get_placement_position",
    # Zone System
    "Zone",
    "SemanticZone",
    "ZoneType",
    "SemanticPosition",
    "OccupancyGrid",
    "TileOccupancy",
    "semantic_to_coordinates",
    "convert_semantic_zone",
    "convert_all_semantic_zones",
    "bfs_reachable",
    "validate_zone_reachability",
    "calculate_z_index",
    # Game Loop Generator
    "GameLoop",
    "LoopStep",
    "LoopStepType",
    "LoopPattern",
    "LOOP_PATTERNS",
    "generate_loop_from_pattern",
    "get_pattern",
    "get_all_patterns",
    "get_patterns_for_scene_type",
    "suggest_pattern",
    "create_custom_loop",
    "generate_compatible_loop",
    "validate_game_loops",
    # Mechanic Compatibility
    "CompatibilityType",
    "ProgressionOrder",
    "CompatibilityRule",
    "CategoryCompatibility",
    "MechanicProgression",
    "CompatibilityResult",
    "CATEGORY_COMPATIBILITY",
    "MECHANIC_COMPATIBILITY",
    "MECHANIC_PROGRESSION",
    "SCENE_MECHANIC_LIMITS",
    "GAME_MECHANIC_LIMITS",
    "SCENE_SAME_MECHANIC_LIMIT",
    "SCENE_MECHANIC_EXCEPTIONS",
    "check_scene_compatibility",
    "check_progression_compatibility",
    "check_game_loop_compatibility",
    "suggest_compatible_mechanics",
    "get_required_tutorials",
    "get_mechanic_complexity",
    "sort_by_progression",
    "check_repetition_limits",
    "check_scene_repetition",
    "check_consecutive_repetition",
    "validate_no_repetition",
    "suggest_alternative_mechanics",
    # Mechanic Graph
    "EdgeType",
    "MechanicEdge",
    "MechanicGraph",
    "DEFAULT_GRAPH",
    "build_default_graph",
    "generate_gameplay_sequence",
    "suggest_next_mechanic",
    "validate_gameplay_sequence",
    # Difficulty Curve
    "CurveType",
    "AudienceType",
    "DifficultyRange",
    "DifficultyCurve",
    "AUDIENCE_PRESETS",
    "create_difficulty_curve",
    "generate_linear_curve",
    "generate_gentle_curve",
    "generate_steep_curve",
    "generate_wave_curve",
    "generate_plateau_curve",
    "validate_game_difficulty",
    "suggest_mechanic_complexity_order",
    "get_recommended_mechanics_for_scene",
    # Layout Patterns
    "LayoutType",
    "ZonePlacement",
    "LayoutZone",
    "Corridor",
    "LayoutPattern",
    "AppliedZone",
    "AppliedCorridor",
    "AppliedLayout",
    "LAYOUT_PATTERNS",
    "get_layout_pattern",
    "get_layout_patterns_for_scene",
    "suggest_layout_pattern",
    "apply_layout_pattern",
    # NPC Behaviors
    "BehaviorState",
    "TriggerType",
    "StateTransition",
    "BehaviorDefinition",
    "BEHAVIORS",
    "get_behavior",
    "get_all_behaviors",
    "get_behavior_for_role",
    "create_patrol_path",
    "get_next_waypoint",
    "advance_patrol",
    # Tutorial Generator
    "TutorialType",
    "TutorialDialogue",
    "TutorialChallenge",
    "TutorialDefinition",
    "TUTORIALS",
    "get_tutorial",
    "get_all_tutorials",
    "needs_tutorial",
    "generate_tutorial_scene",
    "get_tutorial_hints",
    "get_simplified_params",
    # Gameplay Loop Planner (Goal-Driven)
    "GoalType",
    "GameplayStep",
    "GameplayLoop",
    "PlannedLoop",
    "GamePlan",
    "GAMEPLAY_LOOPS",
    "get_loop",
    "get_all_loops",
    "get_loops_by_goal",
    "get_loops_by_tag",
    "suggest_loop",
    "plan_loop",
    "plan_from_goal",
    "expand_goal_to_mechanics",
    "plan_game",
    "get_narrative_context",
    "get_required_npc_roles",
    "validate_loop_against_scene",
    # Scene Populator
    "CellType",
    "PlacedObject",
    "OccupancyGrid",
    "ClusterRule",
    "LandmarkTemplate",
    "PopulatorConfig",
    "PopulatedScene",
    "ScenePopulator",
    "DEFAULT_CLUSTER_RULES",
    "LANDMARKS",
    "ZONE_LANDMARKS",
    "ZONE_DECORATIONS",
    "ZONE_DECORATION_WEIGHTS",
    "poisson_disc_sampling",
    "find_path_bfs",
    "find_path_astar",
    "reserve_corridor",
    "reserve_corridor_natural",
    "cluster_objects",
    "distribute_decorations",
    "terrain_noise",
    "place_landmark",
    "get_landmarks_for_zone",
    "get_decorations_for_zone",
    "populate_scene",
    "get_scene_manifest",
]
