"""
╔═══════════════════════════════════════════════════════════════════════════════╗
║                    DATA-DRIVEN PLACEMENT RULES                                ║
║                                                                               ║
║  NO HARDCODED RULES - Everything comes from asset metadata.                   ║
║                                                                               ║
║  How it works:                                                                ║
║  1. When assets are uploaded, Claude Vision analyzes them                     ║
║  2. Analysis generates placement metadata (requires, provides, avoids)        ║
║  3. This engine reads that metadata to validate placements                    ║
║  4. Works with ANY asset pack - no code changes needed                        ║
╚═══════════════════════════════════════════════════════════════════════════════╝
"""

import logging
from dataclasses import dataclass, field
from typing import Optional, Any

logger = logging.getLogger(__name__)


# ═══════════════════════════════════════════════════════════════════════════════
#  ASSET KNOWLEDGE SCHEMA (stored in database/Pinecone)
# ═══════════════════════════════════════════════════════════════════════════════

@dataclass
class AssetPlacementKnowledge:
    """
    Placement knowledge for an asset - generated by Claude Vision analysis.
    
    This is stored in the asset_knowledge table, NOT hardcoded.
    """
    
    asset_id: str
    asset_name: str
    
    # PLACEMENT TYPE (inferred from visual analysis)
    placement_type: str = "standalone"
    # Options: "standalone", "attached", "grouped", "contextual", "surface"
    
    # REQUIRES: What must be nearby for valid placement
    requires_nearby: list[str] = field(default_factory=list)
    # e.g., ["building", "wall", "structure"] for a door
    
    requires_ground: list[str] = field(default_factory=list)
    # e.g., ["grass", "dirt"] for a tree
    
    attachment_point: str = ""
    # e.g., "front", "top", "side" - where it attaches
    
    # PROVIDES: What this asset enables for others
    provides_attachment: list[str] = field(default_factory=list)
    # e.g., ["front", "side"] for a building
    
    provides_surface: str = ""
    # e.g., "indoor", "bridge" - what ground type it creates
    
    # AVOIDS: What should not be nearby
    avoids_nearby: list[str] = field(default_factory=list)
    # e.g., ["water", "fire"] for wooden objects
    
    avoids_ground: list[str] = field(default_factory=list)
    # e.g., ["water"] for most land objects
    
    # GROUPING
    min_group_size: int = 1
    max_group_size: int = 1
    group_pattern: str = "single"
    # Options: "single", "cluster", "line", "ring", "scatter"
    
    # CONTEXTUAL FUNCTIONS
    context_functions: dict = field(default_factory=dict)
    # e.g., {"over:water": "bridge", "near:fire": "cooking"}
    
    # SPACING
    min_distance_from_similar: float = 0
    # Tiles - prevents clumping
    
    # MESSAGES
    placement_hint: str = ""
    error_message: str = ""


# ═══════════════════════════════════════════════════════════════════════════════
#  EXTRACT PLACEMENT KNOWLEDGE FROM ASSET
# ═══════════════════════════════════════════════════════════════════════════════

def extract_placement_knowledge(asset: dict) -> AssetPlacementKnowledge:
    """
    Extract placement knowledge from asset's existing metadata.
    
    This reads from the 'knowledge' field that was generated by Claude Vision
    when the asset was uploaded and analyzed.
    """
    
    asset_id = asset.get("id", "")
    asset_name = asset.get("name", "unknown")
    knowledge = asset.get("knowledge", {}) or {}
    metadata = asset.get("metadata", {}) or {}
    
    # Read placement fields from knowledge
    # These should be populated by the asset analysis pipeline
    placement = AssetPlacementKnowledge(
        asset_id=asset_id,
        asset_name=asset_name,
        
        # Core placement type
        placement_type=knowledge.get("placement_type", "standalone"),
        
        # Requirements
        requires_nearby=knowledge.get("requires_nearby", []),
        requires_ground=knowledge.get("requires_ground", []),
        attachment_point=knowledge.get("attachment_point", ""),
        
        # What it provides
        provides_attachment=knowledge.get("provides_attachment", []),
        provides_surface=knowledge.get("provides_surface", ""),
        
        # Avoidances
        avoids_nearby=knowledge.get("avoids_nearby", []),
        avoids_ground=knowledge.get("avoids_ground", []),
        
        # Grouping
        min_group_size=knowledge.get("min_group_size", 1),
        max_group_size=knowledge.get("max_group_size", 1),
        group_pattern=knowledge.get("group_pattern", "single"),
        
        # Context
        context_functions=knowledge.get("context_functions", {}),
        
        # Spacing
        min_distance_from_similar=knowledge.get("min_distance_from_similar", 0),
        
        # Messages
        placement_hint=knowledge.get("placement_hint", ""),
        error_message=knowledge.get("error_message", ""),
    )
    
    return placement


# ═══════════════════════════════════════════════════════════════════════════════
#  PLACEMENT VALIDATION (reads from asset metadata)
# ═══════════════════════════════════════════════════════════════════════════════

@dataclass
class PlacementValidation:
    """Result of placement validation."""
    is_valid: bool
    warnings: list[str] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)
    suggestions: list[str] = field(default_factory=list)


def validate_placement(
    asset: dict,
    nearby_assets: list[dict],
    ground_asset: Optional[dict] = None,
    group_size: int = 1,
) -> PlacementValidation:
    """
    Validate if an asset can be placed given its context.
    
    ALL RULES COME FROM ASSET METADATA - nothing hardcoded.
    
    Args:
        asset: The asset being placed (with knowledge metadata)
        nearby_assets: Assets already placed nearby (with knowledge metadata)
        ground_asset: The ground tile at this position (optional)
        group_size: How many of this asset in the current group
    
    Returns:
        PlacementValidation with errors, warnings, and suggestions
    """
    
    result = PlacementValidation(is_valid=True)
    
    # Extract placement knowledge from asset metadata
    placement = extract_placement_knowledge(asset)
    asset_name = placement.asset_name
    
    # No placement rules defined = anything goes
    if placement.placement_type == "standalone" and not placement.requires_nearby:
        return result
    
    # Build set of what's nearby (by name and by what they provide)
    nearby_names = set()
    nearby_provides = set()
    
    for nearby in nearby_assets:
        nearby_names.add(nearby.get("name", ""))
        nearby_knowledge = extract_placement_knowledge(nearby)
        
        # Collect what nearby assets provide
        for provides in nearby_knowledge.provides_attachment:
            nearby_provides.add(provides)
        if nearby_knowledge.provides_surface:
            nearby_provides.add(nearby_knowledge.provides_surface)
    
    # Get ground type if available
    ground_type = ""
    if ground_asset:
        ground_knowledge = ground_asset.get("knowledge", {}) or {}
        ground_type = ground_knowledge.get("terrain_type", "")
        # Also check tile_config
        tile_config = ground_asset.get("metadata", {}).get("tile_config", {})
        if tile_config:
            ground_type = tile_config.get("terrain_type", ground_type)
    
    # ─── CHECK REQUIRES ───────────────────────────────────────────────────────
    
    if placement.requires_nearby:
        # Check if ANY required thing is nearby
        has_required = False
        for required in placement.requires_nearby:
            # Check by name
            if required in nearby_names:
                has_required = True
                break
            # Check by what nearby assets provide
            if required in nearby_provides:
                has_required = True
                break
        
        if not has_required:
            result.is_valid = False
            error_msg = placement.error_message or (
                f"'{asset_name}' requires nearby: {placement.requires_nearby}"
            )
            result.errors.append(error_msg)
            result.suggestions.append(
                f"First place one of: {placement.requires_nearby}, then place '{asset_name}' near it"
            )
    
    # ─── CHECK GROUND REQUIREMENTS ────────────────────────────────────────────
    
    if placement.requires_ground and ground_type:
        if ground_type not in placement.requires_ground and "any" not in placement.requires_ground:
            result.is_valid = False
            result.errors.append(
                f"'{asset_name}' cannot be placed on '{ground_type}'. Requires: {placement.requires_ground}"
            )
    
    # ─── CHECK AVOIDS ─────────────────────────────────────────────────────────
    
    if placement.avoids_nearby:
        for avoid in placement.avoids_nearby:
            if avoid in nearby_names or avoid in nearby_provides:
                result.warnings.append(
                    f"'{asset_name}' should not be placed near '{avoid}'"
                )
    
    if placement.avoids_ground and ground_type:
        if ground_type in placement.avoids_ground:
            result.is_valid = False
            result.errors.append(
                f"'{asset_name}' cannot be placed on '{ground_type}'"
            )
    
    # ─── CHECK GROUPING ───────────────────────────────────────────────────────
    
    if group_size < placement.min_group_size:
        result.warnings.append(
            f"'{asset_name}' looks better in groups of {placement.min_group_size}+"
        )
        result.suggestions.append(
            f"Add {placement.min_group_size - group_size} more '{asset_name}'"
        )
    
    if group_size > placement.max_group_size:
        result.warnings.append(
            f"Too many '{asset_name}' grouped together (max {placement.max_group_size})"
        )
    
    # ─── ADD PLACEMENT HINT ───────────────────────────────────────────────────
    
    if placement.placement_hint and not result.is_valid:
        result.suggestions.append(placement.placement_hint)
    
    return result


# ═══════════════════════════════════════════════════════════════════════════════
#  CONTEXTUAL FUNCTION DETECTION
# ═══════════════════════════════════════════════════════════════════════════════

def get_contextual_function(
    asset: dict,
    nearby_assets: list[dict],
    ground_asset: Optional[dict] = None,
) -> str:
    """
    Determine the contextual function of an asset based on placement.
    
    e.g., log over water → "bridge"
    
    Reads context_functions from asset metadata.
    """
    
    placement = extract_placement_knowledge(asset)
    
    if not placement.context_functions:
        return "default"
    
    # Get ground type
    ground_type = ""
    if ground_asset:
        ground_knowledge = ground_asset.get("knowledge", {}) or {}
        ground_type = ground_knowledge.get("terrain_type", "")
    
    # Check context functions
    # Format: {"over:water": "bridge", "near:fire": "cooking"}
    
    for context_key, function in placement.context_functions.items():
        if ":" in context_key:
            relation, target = context_key.split(":", 1)
            
            if relation == "over" and ground_type == target:
                return function
            
            if relation == "near":
                for nearby in nearby_assets:
                    if target in nearby.get("name", "").lower():
                        return function
                    nearby_tags = nearby.get("tags", [])
                    if target in nearby_tags:
                        return function
    
    return "default"


# ═══════════════════════════════════════════════════════════════════════════════
#  PROMPT GENERATION (reads from asset metadata)
# ═══════════════════════════════════════════════════════════════════════════════

def generate_placement_rules_prompt(assets: list[dict]) -> str:
    """
    Generate placement rules prompt from asset metadata.
    
    NO HARDCODED RULES - reads everything from asset knowledge.
    """
    
    if not assets:
        return ""
    
    lines = [
        "",
        "═══════════════════════════════════════════════════════════════════════════════",
        "ASSET PLACEMENT RULES (from asset metadata)",
        "═══════════════════════════════════════════════════════════════════════════════",
        "",
    ]
    
    # Group assets by placement type
    attached_assets = []
    contextual_assets = []
    grouped_assets = []
    surface_assets = []
    
    for asset in assets:
        placement = extract_placement_knowledge(asset)
        
        if placement.placement_type == "attached" or placement.requires_nearby:
            attached_assets.append((asset, placement))
        elif placement.placement_type == "contextual" or placement.context_functions:
            contextual_assets.append((asset, placement))
        elif placement.placement_type == "grouped" or placement.min_group_size > 1:
            grouped_assets.append((asset, placement))
        elif placement.placement_type == "surface" or placement.requires_ground:
            surface_assets.append((asset, placement))
    
    # Output rules by category
    
    if attached_assets:
        lines.append("❌ ATTACHED ASSETS (NEVER place standalone):")
        for asset, placement in attached_assets[:10]:
            lines.append(f"   • {asset.get('name')}")
            lines.append(f"     REQUIRES nearby: {placement.requires_nearby}")
            if placement.error_message:
                lines.append(f"     Error if violated: {placement.error_message}")
        lines.append("")
    
    if contextual_assets:
        lines.append("🔄 CONTEXTUAL ASSETS (function depends on placement):")
        for asset, placement in contextual_assets[:10]:
            lines.append(f"   • {asset.get('name')}")
            for context, function in placement.context_functions.items():
                lines.append(f"     {context} → becomes '{function}'")
        lines.append("")
    
    if grouped_assets:
        lines.append("👥 GROUPED ASSETS (place in clusters):")
        for asset, placement in grouped_assets[:10]:
            lines.append(
                f"   • {asset.get('name')}: groups of {placement.min_group_size}-{placement.max_group_size}, "
                f"pattern: {placement.group_pattern}"
            )
        lines.append("")
    
    if surface_assets:
        lines.append("🏠 SURFACE-SPECIFIC ASSETS:")
        for asset, placement in surface_assets[:10]:
            lines.append(f"   • {asset.get('name')}")
            if placement.requires_ground:
                lines.append(f"     ONLY ON: {placement.requires_ground}")
            if placement.avoids_ground:
                lines.append(f"     NOT ON: {placement.avoids_ground}")
        lines.append("")
    
    # Build provides lookup
    providers = {}
    for asset in assets:
        placement = extract_placement_knowledge(asset)
        for provides in placement.provides_attachment:
            if provides not in providers:
                providers[provides] = []
            providers[provides].append(asset.get("name"))
        if placement.provides_surface:
            key = f"surface:{placement.provides_surface}"
            if key not in providers:
                providers[key] = []
            providers[key].append(asset.get("name"))
    
    if providers:
        lines.append("📎 ASSETS THAT PROVIDE ATTACHMENT POINTS:")
        for provides, asset_names in providers.items():
            lines.append(f"   • '{provides}' provided by: {', '.join(asset_names[:5])}")
        lines.append("")
    
    lines.extend([
        "═══════════════════════════════════════════════════════════════════════════════",
        "PLACEMENT ORDER:",
        "1. Place assets that PROVIDE attachment points first",
        "2. Then place ATTACHED assets near their requirements",
        "3. Place GROUPED assets in clusters",
        "4. Check ground type for SURFACE-SPECIFIC assets",
        "═══════════════════════════════════════════════════════════════════════════════",
        "",
    ])
    
    return "\n".join(lines)


# ═══════════════════════════════════════════════════════════════════════════════
#  CLAUDE VISION ANALYSIS PROMPT
# ═══════════════════════════════════════════════════════════════════════════════

ASSET_ANALYSIS_PROMPT = """Analyze this game asset image and determine its placement rules.

Return JSON with these fields:

{
  "placement_type": "standalone | attached | grouped | contextual | surface",
  
  "requires_nearby": ["building", "wall"],  // What must be nearby (empty if standalone)
  "requires_ground": ["grass", "dirt"],     // What ground types work (empty if any)
  "attachment_point": "front",              // Where it attaches: front/back/top/side/any
  
  "provides_attachment": ["front", "side"], // What attachment points it provides to others
  "provides_surface": "indoor",             // What ground type it creates (empty if none)
  
  "avoids_nearby": ["water", "fire"],       // What should NOT be nearby
  "avoids_ground": ["water"],               // What ground types don't work
  
  "min_group_size": 1,                      // Minimum for natural look
  "max_group_size": 1,                      // Maximum before crowded
  "group_pattern": "single | cluster | line | ring | scatter",
  
  "context_functions": {                    // Function changes by context
    "over:water": "bridge",                 // e.g., log over water = bridge
    "near:fire": "cooking"                  // e.g., pot near fire = cooking
  },
  
  "min_distance_from_similar": 2,           // Tiles spacing from same asset type
  
  "placement_hint": "Place against a wall or building",
  "error_message": "This asset needs a wall to attach to"
}

Rules for analysis:
- Door/window → placement_type: "attached", requires_nearby: ["building", "wall"]
- Tree/rock → placement_type: "standalone"
- Flowers → placement_type: "grouped", min_group_size: 3
- Log/plank → placement_type: "contextual", context_functions: {"over:water": "bridge"}
- Indoor furniture → placement_type: "surface", requires_ground: ["indoor", "wood_floor"]
- Building → provides_attachment: ["front", "side"], provides_surface: "indoor"

Be specific about what this particular asset needs.
"""


def get_asset_analysis_prompt() -> str:
    """Get the prompt for Claude Vision to analyze asset placement rules."""
    return ASSET_ANALYSIS_PROMPT
